### PR TITLE
Use GHA to run the subtree

### PR DESCRIPTION
**Pull request by lyrixx**
You'll need to create a token and add it the projects secrets

* classic : https://github.com/settings/tokens/new?scopes=repo,workflow&description=gitsplit
* fine grained:
  * https://github.com/settings/personal-access-tokens/new
  * all repo
  * repo > content > read write

The name must be `PRIVATE_TOKEN`

---

fixes https://github.com/acmephp/acmephp/issues/319

### CODE REVIEW

**Comment by Blackbam** [comment]
@lyrixx Will re-check that asap, please remind me in case I forget.

**Comment by lyrixx** [comment]
Friendly ping :)

**Comment by Blackbam** [comment]
@lyrixx Never used that, sorry. Not sure how that works. I have invited you as a project member because you are doing a lot of things here! Can you take care of it now?

**Comment by lyrixx** [comment]
@Blackbam Thanks. I accepted the invitation. For the record, I'll be AFK for the next two month 😍 🌴. I take off on Monday morning.

**Comment by Blackbam** [comment]
@lyrixx Enjoy your time off, I am not allowed to make you an admin probably but I should be able to grant you the permissions required ☺

**Pull request merged**
