### PR TITLE
Dockerfile Change - Get Builds Working Again

### PR DESCRIPTION
**Pull request by programster**
This pull request isn't ideal but "does the job" of getting docker builds working again. I noticed that the official image has not been updated in 3 years. 

Selection_189

... and when I decided to try and do a build. I got a bunch of errors.

The easiest thing for me was to create a new image from Ubuntu which I'm familiar with, and have shared through this pull request. 

You may wish to fix the alpine-based Dockerfile instead and ignore this pull request. That would be a more ideal solution in terms of image filesize, but this will "do the job".

I made sure to test by building and publishing my docker image before using it to generate some certificates. The image can be fetched from [programster/acmephp](https://hub.docker.com/r/programster/acmephp), but be aware that that the is using code from my other pull request for adding DigitalOcean support (the code of which I have put into a separate branch to this).

### CODE REVIEW

**Comment by webii** [comment]
I think that this refactor is maybe too big, or using Ubuntu even not necessary. The only problem with current Dockerfile is using `COPY --from=composer:latest /usr/bin/composer /usr/bin/composer` which means that we are getting the latest composer version. In the same time there is a line `RUN composer global require "hirak/prestissimo"` which generates a problem with the build because `hirak/prestissimo` is supporting only composer 1.x. So removing this requirement is unblocking the build. Moreover this requirement can be just skipped because it is just for some build optimisation totally not required for the build.

The other problem with the code/docker build is that it is not supporting ftp adapter because there is missing `php7-ftp` apk.

**Review by Blackbam — COMMENTED** [review]
Looks good, thank you.

**Comment by Blackbam** [comment]
@tgalopin Can you just have a very short look if this is eligible for being merged?

**Comment by SamMousa** [comment]
I'm going to close this. With the new major release coming soon we can redo this more simply.

**Comment by SamMousa** [comment]
Build are working again, for now they are built for each commit and pushed here: https://github.com/acmephp/acmephp/pkgs/container/acmephp%2Facmephp

Note these are NOT stable releases.

**Pull request closed without merging**
