### PR TITLE
Add https://redirection.io/ as co-maintainer

### PR DESCRIPTION
**Pull request by lyrixx**
See https://github.com/acmephp/acmephp/pulls?q=author%3Alyrixx+

---

I know this approach is a bit daring 😅. But I've been working hard on this project lately.
And I think my company deserves a little praise.

### CODE REVIEW

**Comment by lyrixx** [comment]
tests are fixed in https://github.com/acmephp/acmephp/pull/324

**Comment by Blackbam** [comment]
@lyrixx ZeroSSL has once bought the project but is currently lacking some resources to maintain it - this will change soon. I am very thankful that you invest your time in the maintenance of the project and I am glad to add you, but maybe not in the same line. Can you make a separate sentence in the README.md which says that you are (highly valued) primary supporter?

**Comment by lyrixx** [comment]
I pushed something new. What do you think?

**Comment by Blackbam** [comment]
That works! Thank you again, merged.

**Pull request merged**
