### PR TITLE
Free the resource after reading

### PR DESCRIPTION
**Pull request by elliotfehr**
The openssl resource needs to be released after reading to prevent leaking memory.

### CODE REVIEW

**Comment by jderusse** [comment]
Thank you @elliotfehr. I've push a commit to fix CS (prettyCi) Could you please rebase your PR on top of master to make CI green?

**Comment by elliotfehr** [comment]
@jderusse No problem! I merged in your changes and looks like all checks are passing now. Thank you!

**Comment by jderusse** [comment]
Thank you @elliotfehr

**Comment by elliotfehr** [comment]
@jderusse Thank you for merging! Is it possible to tag a 1.1.2 release with this change in it?

**Comment by jderusse** [comment]
ping @tgalopin

**Comment by elliotfehr** [comment]
I’ve found a work around for my use case and am fine waiting for the next scheduled release. Thanks for the quick responses!

**Pull request merged**
