### PR TITLE
Certificate::getPublicKey and ::getResource

### PR DESCRIPTION
**Pull request by jankal**
I also directly added tests.

### CODE REVIEW

**Comment by tgalopin** [comment]
Thanks @jankal!

**Comment by jankal** [comment]
@tgalopin I made a mistake. `openssl_pkey_get_public` is not extracting a general purpose resource. It just extracts a resource for the public key so the function name (::getResource ()) would be wrong.

I'll fix this on my branch and add a new pull request referencing to this.

**Comment by tgalopin** [comment]
I don't see the new PR, which one are you talking about?

**Comment by jankal** [comment]
I've not created it yet. Was a bit sleepy yesterday evening. I'm going to create it soon.

**Comment by jankal** [comment]
Created #61

**Pull request merged**
