### PR TITLE
Modernize code base

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by SamMousa** [comment]
This is an alternative to #298.

Personally I'm more a fan of ECS, but I don't feel strongly about it. This message is mostly so that we don't attempt to merge both PRs.

**Comment by Blackbam** [comment]
@SamMousa @lyrixx Thanks strict typing etc. is something we should just make sure there are no unexpected new errors due to that changes. Will be on holiday for the next 9 days (will check into Github from time to time though), I am very glad to see all those PRs. Can not verify the functionality and correctnes for any particular case I just check if the code makes sense and does not contain weird changes, let me know if you need anything to get it into the master branch and also as soon as as you feel ready to release 3.0.0.

**Comment by SamMousa** [comment]
@lyrixx looking at this PR; how did you modernize the code exactly? Manually or automated?

**Comment by lyrixx** [comment]
@SamMousa I used rector + php-cs-fixer + lot of manual fixes

**Comment by SamMousa** [comment]
Nice; btw, Rector is made by the same guy as ECS ;-).

I'll leave this closed but wont apply mine either for now. No rush on this.

**Comment by lyrixx** [comment]
> Nice; btw, Rector is made by the same guy as ECS ;-).

I know :)

**Pull request closed without merging**
