### PR TITLE
Release version 2.0

### PR DESCRIPTION
**Pull request by tgalopin**
Fix https://github.com/acmephp/acmephp/issues/210

### CODE REVIEW

**Comment by encedo** [comment]
Hi Titouan,

good to know you are working on EAB for your lib. This is a thing I'm waiting for. My project requires backup for Let's Encrypt and ZeroSSL is a good choice. Moreover, with BuyPass I've three CA in operation. But...

I have got trouble with integration. Precisely, I'm getting `"[External Account Binding] Invalid MAC on JWS request.." ` during `registerAccount()`. EAB credentials are ok, they work with acme.sh. But not here. 

What I have done, I have used 2.0 version of the `acmephp/core` (I know, WiP) and force it to work with Let's Encrypt and BuyPass. Now struggling with ZeroSSL. 

Do you have any reference code for Core? Or any clue how to debug? Not sure if a warring is a root-cause (should not be).
`PHP Deprecated:  Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. in /root/test/vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 57`

Beta tester
Chris :)

**Comment by encedo** [comment]
Hi Titouan,

I have solved the issue. The bug is in class SecureHttpClient in function createExternalAccountPayload().

You have:
```
        $signature = $this->base64Encoder->encode(
            (string) $signer->sign($encodedProtected.'.'.$encodedPayload, $externalAccount->getHmacKey() )
        );
```
should be:
```
        $signature = $this->base64Encoder->encode(
            (string) $signer->sign($encodedProtected.'.'.$encodedPayload, $this->base64Encoder->decode( $externalAccount->getHmacKey() ))
        );
```
Look at RFC8555 at section 7.3.4:
```
   To enable ACME account binding, the CA operating the ACME server
   needs to provide the ACME client with a MAC key and a key identifier,
   using some mechanism outside of ACME.  The key identifier MUST be an
   ASCII string.  The MAC key SHOULD be provided in base64url-encoded
   form, to maximize compatibility between non-ACME provisioning systems
   and ACME clients.
```

Update the code regards my patch and the acmephp/core is ZeroSSL compliant :) Your test code is limited to the test environment of Pebble instance config, where the MAC is just a string, not a real base64 string.

Chris

**Comment by tgalopin** [comment]
Ah, awesome, thanks for the help! I'll have a look asap

**Comment by encedo** [comment]
You welcome :)

I have one more idea worthy to add to the lib - possibility to get a cert based on CSR in PEM format (I do even have a dirty hack of this) :)

The CSR is generated on the other system (in my case embedded device) and send out to the 'singer'. The 'signer' issue a cert (from LE, BuyPass or ZeroSSL, starting from tomorrow), handle DNS validation and reply with a cert. The private key in always unknown to the 'signer', generated and stored inside a embedded device. 

My dirty hack is inside the finalizeOrder() function - I've added new 4th argument $csr_pem to the function, and if set, internal variable $csrContent is not generated based on $csr but taken from that new argument directly. Simple, rock solid, but dirty :) 

Chris

**Comment by tgalopin** [comment]
> possibility to get a cert based on CSR in PEM

If you wish to propose a PR I'd be happy to review it!

I just pushed an update that indeed fixes the issue about EAB, thanks!

**Comment by echel0n** [comment]
This is still an issue with `Implicit conversion of keys from strings is deprecated`, the following changes resolve the issue

before:
```
        $signature = $this->base64Encoder->encode(
            (string) $signer->sign($encodedProtected.'.'.$encodedPayload, $this->base64Encoder->decode($externalAccount->getHmacKey()))
        );
```

after:
```
        $signature = $this->base64Encoder->encode(
            (string) $signer->sign($encodedProtected.'.'.$encodedPayload, InMemory::plainText($this->base64Encoder->decode($externalAccount->getHmacKey())))
        );
```

**Pull request merged**
