### PR TITLE
Fix serializer

### LINKED ISSUE #308: Issue with using Symfony Serializer
When attempting to regenerate SSL certificate after 3 months I'm getting these errors both on master (PHP 8.3) and latest release (PHP 7.4):

```
Registering contact my@email.com...
Loading account key pair...  
Registering on the ACME server...
Account registered successfully!

In Repository.php line 238:
                                                            
  Loading of domain my.domain.com distinguished name failed  
                                                            

In Serializer.php line 224:
                                                                                                         
  Could not denormalize object of type "AcmePhp\Ssl\DistinguishedName", no supporting normalizer found.  
                                                                                                         

run [-d|--delay DELAY] [--] <config>
```

The issue is with dependencies. If I stay on 2.1.0 with these dependency versions (`composer show -i` command), then all works:

```
adbario/php-dot-notation          2.2.0   PHP dot notation access to arrays
alibabacloud/cdn                  1.8.958 Alibaba Cloud Cdn SDK for PHP
alibabacloud/client               1.5.31  Alibaba Cloud Client for PHP - Use Alibaba Cloud in your PHP project
alibabacloud/wafopenapi           1.8.884 Alibaba Cloud WafOpenapi SDK for PHP
aws/aws-crt-php                   v1.0.2  AWS Common Runtime for PHP
aws/aws-sdk-php                   3.198.6 AWS SDK for PHP - Use Amazon Web Services in your PHP project
clagiordano/weblibs-configmanager v1.2.0  weblibs-configmanager is a tool library for easily read and access to php config ar...
composer/ca-bundle                1.2.11  Lets you find a path to the system CA bundle, and includes a fallback to the Mozill...
danielstjules/stringy             3.1.0   A string manipulation library with multibyte support
daverandom/libdns                 v2.0.2  DNS protocol implementation written in pure PHP
doctrine/instantiator             1.4.0   A small, lightweight utility to instantiate objects in PHP without invoking their c...
doctrine/lexer                    1.2.1   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent P...
egulias/email-validator           3.1.2   A library for validating emails against several RFCs
guzzlehttp/guzzle                 7.3.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises               1.5.0   Guzzle promises library
guzzlehttp/psr7                   1.8.3   PSR-7 message implementation that also provides common utility methods
lcobucci/jwt                      3.4.6   A simple library to work with JSON Web Token and JSON Web Signature
league/flysystem                  1.1.5   Filesystem abstraction: Many filesystems, one API.
league/flysystem-memory           1.0.2   An in-memory adapter for Flysystem.
league/flysystem-sftp             1.0.22  Flysystem adapter for SFTP
league/mime-type-detection        1.8.0   Mime-type detection for Flysystem
monolog/monolog                   1.26.1  Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/jmespath.php            2.6.1   Declaratively specify how to extract elements from a JSON document
padraic/humbug_get_contents       1.1.2   Secure wrapper for accessing HTTPS resources with file_get_contents for PHP 5.3+
padraic/phar-updater              v1.0.6  A thing to make PHAR self-updating easy and secure.
phpdocumentor/reflection-common   2.2.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock 5.2.2   With this component, a library can provide support for annotations via DocBlocks or...
phpdocumentor/type-resolver       1.5.1   A PSR-5 based resolver of Class names, Types and Structural Element Names
phpseclib/phpseclib               2.0.33  PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFT...
phpspec/prophecy                  1.14.0  Highly opinionated mocking framework for PHP 5.3+
psr/container                     1.1.1   Common Container Interface (PHP FIG PSR-11)
psr/http-client                   1.0.1   Common interface for HTTP clients
psr/http-message                  1.0.1   Common interface for HTTP messages
psr/log                           1.1.4   Common interface for logging libraries
ralouphie/getallheaders           3.0.3   A polyfill for getallheaders.
sebastian/comparator              3.0.3   Provides the functionality to compare PHP values for equality
sebastian/diff                    3.0.3   Diff implementation
sebastian/exporter                3.1.3   Provides the functionality to export PHP variables for visualization
sebastian/recursion-context       3.0.1   Provides functionality to recursively process PHP variables
swiftmailer/swiftmailer           v6.2.7  Swiftmailer, free feature-rich PHP mailer
symfony/config                    v5.3.4  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                   v5.3.7  Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection      v5.3.8  Allows you to standardize and centralize the way objects are constructed in your ap...
symfony/deprecation-contracts     v2.4.0  A generic function and convention to trigger deprecation notices
symfony/filesystem                v5.3.4  Provides basic utilities for the filesystem
symfony/finder                    v5.3.7  Finds files and directories via an intuitive fluent interface
symfony/phpunit-bridge            v5.3.8  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype            v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv            v1.23.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme    v1.23.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn         v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer  v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring         v1.23.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72            v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73            v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80            v1.23.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81            v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/serializer                v5.3.8  Handles serializing and deserializing data structures, including object graphs, int...
symfony/service-contracts         v2.4.0  Generic abstractions related to writing services
symfony/string                    v5.3.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points ...
symfony/var-dumper                v5.3.8  Provides mechanisms for walking through any arbitrary PHP variable
symfony/yaml                      v5.3.6  Loads and dumps YAML files
webmozart/assert                  1.10.0  Assertions to validate method input/output with nice error messages.
webmozart/path-util               2.3.0   A robust cross-platform utility for normalizing, comparing and modifying file paths.
```

### PR DESCRIPTION
**Pull request by lyrixx**
fixes #308

### CODE REVIEW

**Comment by aik099** [comment]
Is this change backward compatible with the lowest supported dependency versions?

**Comment by lyrixx** [comment]
Wep 👍🏼 This normalizer is in symfony for ages

**Comment by SamMousa** [comment]
LGTM, out of curiosity @lyrixx when you crated this, did you check "allow contributors to push"? 
-> wondering why ther PHAR creation fails.

**Comment by lyrixx** [comment]
> did you check "allow contributors to push"?

It was not checked indeed, I don't know why. Usually It's always checked by default

**Pull request merged**
