### PR TITLE
Automatically agreed with agrement

### PR DESCRIPTION
**Pull request by jderusse**

### CODE REVIEW

**Comment by tgalopin** [comment]
Awesome! I didn't find it in the protocol when I searched, is it a norm?

**Comment by jderusse** [comment]
A little bit described in acme documentation. But in reality, I reverse engineered a client found on GitHub

**Comment by tgalopin** [comment]
:+1: 

I'm not sure why Travis is failing, I'll check.

**Comment by jderusse** [comment]
Wrong user used on sftp container (already fixed in an other PR: file /test/setup.sh)

**Comment by tgalopin** [comment]
Can you fix it here and rebase (or even create another PR?). This one seems ready but I would like to take a better look on the bigger ones.

**Comment by jderusse** [comment]
see #27

**Comment by tgalopin** [comment]
Can you rebase?

**Comment by jderusse** [comment]
done

**Comment by tgalopin** [comment]
Thanks!

**Pull request merged**
