### PR TITLE
Allow multi-domain in cli

### PR DESCRIPTION
**Pull request by jderusse**
* [x] Tests

The distinguishedName is asked only the first time. Even if one of the fields is empty

### CODE REVIEW

**Comment by jderusse** [comment]
RFR @tgalopin

**Comment by tgalopin** [comment]
This PR seems great but I would like to add the alternative domains in the status command (`bin/acme status` should display the original domain and the alternative ones).

I thought of something like:

```

**Comment by jderusse** [comment]
Her we go..

```
+---------------------+----------------------------+---------------------+---------------------+----------------+
| Domain              | Issuer                     | Valid from          | Valid to            | Needs renewal? |
+---------------------+----------------------------+---------------------+---------------------+----------------+
| titouangalopin.com  | Let's Encrypt Authority X3 | 2016-08-16 18:45:00 | 2016-11-14 18:45:00 | No             |
| maindomain.com      | Let's Encrypt Authority X3 | 2016-08-16 18:45:00 | 2016-11-14 18:45:00 | No             |
|  ├── altdomain1.com |                            |                     |                     |                |
|  └── altdomain2.com |                            |                     |                     |                |
| anotherdomain.com   | Let's Encrypt Authority X3 | 2016-08-16 18:45:00 | 2016-11-14 18:45:00 | No             |
+-------------------------------+----------------------------+---------------------+---------------------+----------------+
```

**Comment by tgalopin** [comment]
I tested this and almsot everything is fine for me. I have a small concern about renewal.

Imagine a user having requested a certificate for the domain acmephp.com. He has the following status:


```
+--------------------+----------------------------+---------------------+---------------------+----------------+
| Domain             | Issuer                     | Valid from          | Valid to            | Needs renewal? |
+--------------------+----------------------------+---------------------+---------------------+----------------+
| acmephp.com        | Let's Encrypt Authority X3 | 2016-08-24 08:42:00 | 2016-11-22 08:42:00 | No             |
+--------------------+----------------------------+---------------------+---------------------+----------------+
```

What should happen if he executes `bin/acme request acmephp.com -a example.com`?

IMO there are two possibilities:

1. The request is considered a first request and a new multi-domain certificate is requested, overwriting the previous single domain certificate. This is the current behavior.
2. The additionnal domain is ignored and the command try to renew the certificate of the single domain acmephp.com.

I'm not sure which option should be adopted. WDYT?

**Comment by jderusse** [comment]
IMO, if the user want A+B the we must request a certificate for A only. So 2. is not acceptable.

This PR use the previous distinguishedName and add the new alternative domain. So it's not technically a new request (given we don't ask the user to enter the country and other fields) but we act like it.

**Comment by tgalopin** [comment]
Okay, seems good to me indeed.

**Comment by tgalopin** [comment]
Thanks @jderusse!

**Pull request merged**
