### PR TITLE
fix: update self-update command and phar generation config

### PR DESCRIPTION
**Pull request by SamMousa**
This replaces the unmaintained self updater and uses a different popular package for self-updating: 
https://github.com/consolidation/self-update

### CODE REVIEW

**Comment by Blackbam** [comment]
@SamMousa Thank you very much for the PR can you please check why the tests are failing? Configuration does not allow a merge. If there are obsolete tests we can remove them.

**Comment by SamMousa** [comment]
The tests are failing due to old dependencies, they are currently failing on master as well.

**Comment by Blackbam** [comment]
@SamMousa Can we remove / update those dependencies first? Can do it as well but it may take some time until I can check that.

**Comment by SamMousa** [comment]
Feel free to take your time, I don't use the CLI and have the decided to focus my efforts / the time that I have available on the Core.

**Comment by SamMousa** [comment]
One could even argue that we should abandon the CLI altogether. It doesn't do anything that 50 other tools in 10 languages already do:
https://acmeclients.com/categories/cli/

**Comment by SamMousa** [comment]
I've rebased this PR to resolve the conflicts.

**Comment by Blackbam** [comment]
@SamMousa Checks are green in the master now, can you check why they fail here? No hurries, I am thankful for everyone contributing.

**Comment by SamMousa** [comment]
@Blackbam ready for merge!

**Pull request merged**
