### PR TITLE
Add option that allows a client to download the alternate certificate link instead of the default one

### PR DESCRIPTION
**Pull request by TJP85**
This will allow a client to request an alternate certificate if the CA provides one, and if not it will download the default one.

### CODE REVIEW

**Comment by tgalopin** [comment]
Hello @TJP85 !

I'm trying to understand what you call an Alternate Certificate: is that a SAN certificate? Are you implementing https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.7.4.2 ?

**Comment by TJP85** [comment]
Hi @tgalopin. Yes, its the same SAN certificate, its just cross signed with IdenTrust’s DST Root X3 instead of only being signed with Let's Encrypt's root (ISRG Root X1 cert).

https://github.com/acmephp/acmephp/issues/210

**Comment by tgalopin** [comment]
Hi @TJP85 !

I'm closing this in favor of https://github.com/acmephp/acmephp/pull/209 where I imported your commit, as this change requires a Backward Compatibility break thus I'll release it in v2.

Thanks for your PR!

**Comment by tgalopin** [comment]
Oh and also, it fou wish to review it, that would be awesome, and the two concerned commits are:

* https://github.com/acmephp/acmephp/pull/212/commits/6dfb900de4cbefcf36707441887f803692f99e1d
* https://github.com/acmephp/acmephp/pull/212/commits/a526a6b5887a0640f9b7c97e5b82090df3143fed

**Pull request closed without merging**
