### PR TITLE
Remove php-cs-test (replacer by prettyci)

### PR DESCRIPTION
**Pull request by jderusse**

### CODE REVIEW

**Comment by jderusse** [comment]
Something is weird with PrettyCi. Running the fixer locally detect 23 failures, whereas PrettyCi is green.

Maybe the the version of php-cs-fixer ping @mnapoli

**Comment by mnapoli** [comment]
@jderusse oh that's interesting I don't see any failure locally too.

My version of PHP-CS-Fixer is 2.12.2, which one is yours?

And thanks for the ping

**Comment by mnapoli** [comment]
That’s a really good idea! I’ll update the runner as soon as I can, in the meantime you can use .prettyci.composer.json to install a specific version (it is documented on the website)

**Comment by mnapoli** [comment]
PrettyCI should be running the latest version now!

**Comment by tgalopin** [comment]
It is, thanks :) . I removed php-cs-fixer to use PrettyCI in https://github.com/acmephp/acmephp/pull/135

**Pull request closed without merging**
